/**
 * Dialog for saving AI-generated prose as a named draft.
 * Appears after generation completes — user can customize the name before saving.
 */
import { useState } from 'react';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
    DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useDraftStore } from '@/features/drafts/stores/useDraftStore';
import { useStoryContext } from '@/features/stories/context/StoryContext';
import { toast } from 'react-toastify';

interface SaveDraftDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    content: string;
    sceneBeatCommand?: string;
    modelName?: string;
    modelProvider?: string;
    promptId?: string;
    promptName?: string;
    lorebookContext?: string[];
}

function generateDefaultName(): string {
    const now = new Date();
    const formatted = now.toLocaleString('en-US', {
        month: 'short',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        hour12: true,
    });
    return `Draft – ${formatted}`;
}

export function SaveDraftDialog({
    open,
    onOpenChange,
    content,
    sceneBeatCommand,
    modelName,
    modelProvider,
    promptId,
    promptName,
    lorebookContext,
}: SaveDraftDialogProps) {
    const [name, setName] = useState(() => generateDefaultName());
    const [saving, setSaving] = useState(false);
    const { currentStoryId, currentChapterId } = useStoryContext();
    const { saveDraft } = useDraftStore();

    // Reset name when dialog opens
    const handleOpenChange = (v: boolean) => {
        if (v) setName(generateDefaultName());
        onOpenChange(v);
    };

    const handleSave = async () => {
        if (!currentStoryId || !currentChapterId) {
            toast.error('No story or chapter selected');
            return;
        }
        if (!name.trim()) {
            toast.error('Please enter a draft name');
            return;
        }

        setSaving(true);
        try {
            await saveDraft({
                storyId: currentStoryId,
                chapterId: currentChapterId,
                name: name.trim(),
                content,
                sceneBeatCommand,
                modelName,
                modelProvider,
                promptId,
                promptName,
                lorebookContext,
                wordCount: content.split(/\s+/).filter(Boolean).length,
            });
            toast.success('Draft saved');
            onOpenChange(false);
        } catch {
            toast.error('Failed to save draft');
        } finally {
            setSaving(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={handleOpenChange}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Save Draft</DialogTitle>
                    <DialogDescription>
                        Give this draft a name so you can find it later.
                    </DialogDescription>
                </DialogHeader>
                <div className="py-4">
                    <Label htmlFor="draft-name" className="text-sm font-medium">
                        Draft Name
                    </Label>
                    <Input
                        id="draft-name"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        onKeyDown={(e) => {
                            if (e.key === 'Enter') handleSave();
                        }}
                        className="mt-2"
                        autoFocus
                    />
                    <p className="text-xs text-muted-foreground mt-2">
                        {content.split(/\s+/).filter(Boolean).length} words
                        {modelName && <> · Generated by {modelName}</>}
                    </p>
                </div>
                <DialogFooter>
                    <Button variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
                        Cancel
                    </Button>
                    <Button onClick={handleSave} disabled={saving || !name.trim()}>
                        {saving ? 'Saving…' : 'Save Draft'}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
